# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          node-version: '18.20.0'
      - run: npm install
      - run: npm test

workflows:
  build-deploy:
    jobs:
      - build:
          context: st-global
